# Generated by Django 3.2.9 on 2022-05-22 00:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='sobrenome',
            field=models.CharField(default='', max_length=255, verbose_name='Sobrenome'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 21, 21, 5, 9, 692740), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
    ]
