# Generated by Django 3.2.9 on 2022-05-22 16:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20220521_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 13, 25, 17, 575871), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='is_active',
            field=models.BooleanField(default=True, help_text='<br/>Marque para Ativar/Desmarque para Desativar o gênero', verbose_name='Ativo'),
        ),
    ]
