# Generated by Django 3.2.9 on 2022-05-22 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 13, 27, 19, 818866), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o gênero', verbose_name=''),
        ),
    ]
