# Generated by Django 3.2.9 on 2022-05-22 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20220522_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o empréstimo', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='autor',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o autor', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 13, 29, 41, 387907), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o idioma', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='livro',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o livro', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Desativar o usuário', verbose_name=''),
        ),
    ]
