# Generated by Django 3.2.9 on 2022-05-22 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20220522_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='emprestado',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 14, 21, 4, 776328), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
    ]
