# Generated by Django 3.2.9 on 2022-05-22 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_alter_emprestimo_dataemprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 20, 7, 51, 3790), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(help_text='Selecione um gênero para o livro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.genero', verbose_name='Gênero'),
        ),
    ]
