# Generated by Django 3.2.9 on 2022-06-10 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0014_auto_20220522_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataDevolucao',
            field=models.DateField(blank=True, help_text='Informe a data de devolução do livro', null=True, verbose_name='Data de Devolução'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataEmprestimo',
            field=models.DateField(default=datetime.datetime(2022, 6, 9, 21, 0, 15, 496938), help_text='Informe a data de empréstimo do livro', verbose_name='Data do Empréstimo'),
        ),
    ]
