# Generated by Django 3.2.9 on 2022-06-11 23:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0019_auto_20220610_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataPrazoDevolucao',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 18), help_text='Informe a data máxima de devolução do livro', null=True, verbose_name='Data Máxima de Devolução'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('reservaID', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, help_text='Marque para Ativar/Desmarque para Cancelar a reserva', verbose_name='')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Data de Criação')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Data de Modificação')),
                ('livro', models.ForeignKey(help_text='Selecione o livro a reservar', null=True, on_delete=django.db.models.deletion.RESTRICT, to='cadastros.livro', verbose_name='Livro')),
                ('nomeSolicitante', models.ForeignKey(blank=True, help_text='Selecione o nome do usuário', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.usuario', verbose_name='Usuário')),
            ],
        ),
    ]
