# Generated by Django 3.2.9 on 2022-06-11 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_auto_20220611_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['createdAt'], 'verbose_name': 'Reserva'},
        ),
        migrations.AlterModelTable(
            name='reserva',
            table='Reserva',
        ),
    ]
