# Generated by Django 3.2.9 on 2022-06-11 23:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20220611_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='dataReserva',
            field=models.DateField(default=datetime.date.today, help_text='Informe a data da reserva do livro', verbose_name='Data da Reserva'),
        ),
    ]
