# Generated by Django 3.2.9 on 2022-06-12 17:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0022_reserva_datareserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='dataPrazoDevolucao',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 19), help_text='Informe a data máxima de devolução do livro', null=True, verbose_name='Data Máxima de Devolução'),
        ),
    ]
