# Generated by Django 3.2.9 on 2022-06-16 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_alter_emprestimo_dataprazodevolucao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimo',
            old_name='nomeEmprestador',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='dataPrazoDevolucao',
            field=models.DateField(blank=True, default=datetime.date(2022, 6, 22), help_text='Informe a data máxima de devolução do livro', null=True, verbose_name='Data Máxima de Devolução'),
        ),
    ]
